### PR TITLE
Each component have its own css file in dist/components

### PR DESCRIPTION
**Pull request by TotomInc**
## Brief description

As #96 says, this was needed if people wanted to import only a css component. The vuejs version of papercss need this since we want to import, for example, `buttons.css` styling into our `button` component. I also edited a lot of `src` files, I imported their dependencies. I need advice on this because I think it's the wrong way of doing it.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by TotomInc** [comment]
Well, it's like in JS, we should import the dependencies only where they are used, and avoid making them global. It's kind of the same thing in less/sass.

**Comment by TotomInc** [comment]
Well, I'll resolve the conflicts when I got some time, I will also include the own dependencies of the latest merged features. Once it's done, I'll merge it. I've got a question @rhyneav , when this PR will be merged, is it possible to deploy a new version? I need this PR to be merged on papercss/vuejs-papercss#3

**Comment by rhyneav** [comment]
Right on. Is there a way to scope variables in Less so that they are not all global? 

And what do you mean by deploy a new version? Like launch v1.2.1?

**Comment by TotomInc** [comment]
Yep something like v1.2.1 or v1.3.0 if there are enough features added. I don't know if there is a way to scope variables with less, but actually we need (and it's also a best practice) to import the dependencies of each component inside the said component. In our case, we are talking about colors, mixins like borders and shadow. I'd like to have the opinion of @Fraham about this.

**Comment by TotomInc** [comment]
@rhyneav I've just done a pull from develop and made the changes needed. Once the tests are passed, I'll merge it.

**Pull request merged**
