### PR TITLE
Colors change

### PR DESCRIPTION
**Pull request by Famaxis**
## Brief description

Colors improving. More bright colors, changes in contrast for better readability, especially for the dark mode.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

 1 - Before & after

1-before
1-after

2 - Before & after

2-before
2-after

3 - Before & after

3-before
3-after

## Further details

There can be a question: is that a good idea — changing neutral dark grey to warmer brown? The thing is, that only a minority of people make modifications to the used frontend frameworks. Most people use it as it is, having no time for design, so, I think, frameworks shouldn't be too neutral and grey. It's good to offer ready color scheme.

### CODE REVIEW

**Comment by rhyneav** [comment]
Thank you for the PR here!

I do agree that the colors need some improvement with contrast, but this change seems a little too drastic for the style of the framework. The color contrast of the existing `secondary` is where we'd want to be for the other colors. The goal being changing any of the alert styles should have a uniform luminosity and readability. At an initial glance, I think that would translate to the following for the current PaperCSS colors for light mode, but it's tough to say without experimentation. 

Primary
- background: needs to be lighter
- color: no change

Secondary
- background: no change
- color: no change

Success
- background: needs to be slightly lighter and more green
- color: needs to be darker

Warning
- background: needs to be ever so slightly ligher
- color: needs to be darker

Danger
- background: needs to be ever so slightly ligher
- color: no change

**Comment by Famaxis** [comment]
So, I took `secondary` as an example and did no change in it. In the other colors I did the same brightness and saturation with a small adjustment. I had to change `danger` color, because it was too dark in comparison to other colors. Am I working in right direction?

**Comment by rhyneav** [comment]
Nice! Thank you for the updates, this is looking really good! 

I think the only change I would make here is to make the `success` background a little more green, it feels just a touch too pastel in my opinion. But otherwise this is a huge improvement in terms of readability!

**Comment by Famaxis** [comment]
Ok, I'll change it a little and will create a new PR.

**Comment by Famaxis** [comment]
There was no need to create new PR, I just added a new commit and removed previous one. 
No changes were made to dark theme (for now).
A little change in `success`.

**Comment by rhyneav** [comment]
Nice, thank you! I think this is looking good! I may tweak the success color ever so slightly to be darker after merging. But it's something so minor I'm not sure if it's worth going back and forth in discussion over it.

I'm glad you brought up dark mode too, were you also planning on updating those colors?

**Comment by Famaxis** [comment]
Yes, I can work with dark mode too. Any suggestions, what should I take as an example?

**Comment by rhyneav** [comment]
It might make sense to start with just adding examples of colors to the dark mode page of the docs for reference. From there, I think just making the new colors just a touch darker would work!

**Comment by Famaxis** [comment]
Shouldn't text color and background color be inverted in dark mode? I mean light text and dark background.
Maybe, I need to change 
`$dark-success-text: $dark-success-dark-10`
to
`$dark-success-text: $dark-success-light-10`? 
And make background color darker. Or there is no need to invert?

**Comment by rhyneav** [comment]
Inverting is not a crazy idea, would definitely be worth exploring! Typically though I've usually seen dark mode as the same colors as light, just a bit more muted/darker so they don't pop out of the screen

**Comment by Famaxis** [comment]
Ok, for now I did it without inverting. I took colors from my last commit for light mode, made it more muted and a little darker. Instead of 
`$dark-success-text: $dark-success-dark-10`
I did
`$dark-success-text: $dark-success-dark`
for better contrast.

Before I create commit, I would like to hear your notes.

1 - Before & after

before

after

2 - Before & after

before

after

**Review by rhyneav — APPROVED** [review]
Nice, this is looking awesome! Thank you for the updates! 

I'm going to pull it in locally to confirm everything looks okay across all components, but will merge this in and get a release out as soon as I can!

**Comment by Famaxis** [comment]
I added a second commit, for dark mode.

**Comment by almibarss** [comment]
I'm sorry to be late to the party but I'm still getting poor results with the latest release:

papercss

**Comment by rhyneav** [comment]
Thank you for the report, @almibarss! I'll take a look and get a fix out

**Comment by rhyneav** [comment]
What does your HTML look like @almibarss so I can try to reproduce this? The current alerts in dark mode look like this in the latest release

Screen Shot 2022-12-08 at 08 12 35

**Comment by almibarss** [comment]
```html
<input id="alert-short-state" class="alert-state" type="checkbox" checked>
<div data-testid="alert-success" id="alert-short" class="alert alert-success dismissible">
  <a></a>
  <div>
    <label class="btn-close" for="alert-short-state">
      <i class="fa fa-clipboard"></i>
    </label>
    <label class="btn-close" for="alert-short-state">X</label>
  </div>
</div>
```

**Comment by rhyneav** [comment]
Thank you for the snippet @almibarss! I was able to see on my end that we were missing a mixin on the `btn-close` class. I combed through the rest of the docs in dark mode as well to make sure there weren't any other issues hiding in there. A new deploy will go out this week with the fix!

**Comment by almibarss** [comment]
Mmm... I'm not 100% convinced yet. Take a look at the screenshots below. IMO there's too much contrast in the new version between the close button(s) and the rest of the alert. On the other hand there's too little contrast between the regular icon and the hover one.
Also the colors for the regular and the hover (`--success-text` and `--success-dark`) in dark mode happen to be the same: `#265927`
papercss2

**Pull request merged**
