### PR TITLE
Feature started implementation for unit tests

### LINKED ISSUE #19: Unit Tests
I have just read this blog post: http://tomek.wiszniewski.cc/how-css-unit-tests-helped-us-move-fast/
This goes over how its possible to write unit tests for css, this would be really handy in this project as it will allow us to have our LESS code tested automatically

### PR DESCRIPTION
**Pull request by Fraham**
## Brief description

I have now started the implementation, this is my first time creating unit tests in js so they might be perfect.

This is just a basic startup of the tests, only tests that the font colour gets set correctly.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

Closes #19

### CODE REVIEW

**Comment by Fraham** [comment]
@rhyneav I have started the unit test process, is there someway you could hook these up to a CI runner so that the tests can be run automatically?

**Comment by rhyneav** [comment]
> this is my first time creating unit tests in js so they might be perfect

Confident, they probably are perfect ;)

And you bet! I'll get that hooked up for you.

**Comment by Fraham** [comment]
It seems fairly simple to get Travis to run the karma unit tests for us
http://karma-runner.github.io/0.8/plus/Travis-CI.html

**Comment by Fraham** [comment]
@rhyneav I think you need to enable for paper-css to be enable on travis for it to work

**Comment by rhyneav** [comment]
Got the notification and approved it. Travis looks good for this.

**Comment by Fraham** [comment]
I think you need to go here to enabled it for the css project
https://travis-ci.org/profile/papercss

**Comment by rhyneav** [comment]
Sounds good, I've enabled it via Travis CI.
image

On another note, is there any specific reason why quixote is included within the test folder and not as a installed module?

**Comment by Fraham** [comment]
Finally got it working :)

**Comment by Fraham** [comment]
Not the best code in the world but its a start, had to have quixote and chai in the vendor folder, was causing issues without it. will try and remove them

**Comment by Fraham** [comment]
@rhyneav can i merge this, i know it can be done better but its a start and will allow people with experience to fix the code

**Comment by TotomInc** [comment]
Good news we have working tests!

**Comment by rhyneav** [comment]
That sounds good! We'll probably need to add in documentation on the tests, but that can be a separate issue/PR.

**Pull request merged**
