### PR TITLE
link - change underline style to match button style

### PR DESCRIPTION
**Pull request by serotonyn**
## Brief description
Fixes: #155 
...

## Developer Certificate of Origin

- [ ] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures
image

...

## Further details
I made a change to the link element so it matches the button element. The way I did this is by removing the ```background-image``` from the ```a``` in _buttons.scss and then adding an ```:after``` pseudo-element.
...

### CODE REVIEW

**Comment by rhyneav** [comment]
Thank you for the PR @serotonyn! I really like the look of the new link, but think that there are some small things that need addressed before we get this merged in.

When looking at the docs (on chrome), I noticed that anchor buttons are also getting the `:after` pseudo element added with the underline. This could be remedied by setting the background to none on the `:after` for classes with `paper-btn`.
screenshot from 2018-11-18 16 41 39

I also noticed that the underline does not wrap for multi-line links. Thinking back on it, I think that is why I went with a background image originally. It solves a lot of edge cases around link underlines. 
screenshot from 2018-11-18 16 44 18

Here's [a good resource](https://css-tricks.com/styling-underlines-web/) about styling link underlines. Even the author concludes that there's no great way to style these, but that a background image "comes the closest to everything we want and with the fewest gotchas". Maybe making an SVG of a hand drawn underline might be a good bet here.

**Comment by TotomInc** [comment]
@serotonyn tests have failed, here are the errors (its mostly due to the code format):

```
src/components/_buttons.scss
 63:25  ✖  Expected quotes                  function-url-quotes                
 65:3   ✖  Expected background-position to  order/properties-alphabetical-order
           come before background-repeat
```

**Comment by serotonyn** [comment]
@rhyneav thank you for the article. Reading it was really uplifting.
So I too decided to go width the background image.
The style of the underlink has changed a little bit though, since I'm no longer using a pseudo element.

ps: I can't make build the project on my computer. When I try to run `npm start` this is what I get :
```
gulp[1128]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100033c31 node::Abort() [/usr/local/bin/node]
 2: 0x100032c77 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x100058a4b node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x10022822f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1002273c8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x100226d97 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x297069f841bd
fish: 'npm start' terminated by signal SIGABRT (Abort)
```

**Comment by TotomInc** [comment]
What is your Node version? This errors seems to pop on Node 10.

You could also try this (don't commit anything after doing this please):

```bash
rm -rf node_modules
rm -rf package-lock.json
npm cache clean
npm install
```

**Comment by serotonyn** [comment]
I'm in deed using node version 10. (v10.5.0).
I think I've already tried this. But I'm going to give it another try !
ps : `npm cache clean` returns
 ```npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.```

**Comment by TotomInc** [comment]
Oops I forgot that you need to pass `--force` to actually execute the cache clean.

Try to run `npm cache clean --force` then `npm install` (after you removed the `node_modules` and the `package-lock.json`).

Also make sure you are using the latest LTS version of Node, which is actually v10.13.0 with npm 6.4.1.

**Comment by serotonyn** [comment]
Yes ! It's working now. Thank you @TotomInc

**Comment by TotomInc** [comment]
Try to commit your `package-lock.json`, we will see if dependencies versions changed and if tests can pass.

Also is the feature finished? Or you need to make other commits?

**Comment by serotonyn** [comment]
I am not sure if this is what you asked, but i just pushed a commit that tracks only `package-lock.json`.
Yes, actually my Pr isn't working now. I have to do another commit.

**Comment by serotonyn** [comment]
Hi @TotomInc, do you think I can now make commits ?

**Comment by rhyneav** [comment]
Maybe the [deploy preview](https://deploy-preview-169--astronaut-pig-36111.netlify.com/) didn't build correctly, but I'm unable to see what the new link style looks like. Could you please provide a screenshot @serotonyn 

And I apologize for the delay in responding!

**Comment by TotomInc** [comment]
Closing the PR as it is abandoned by the author. Feel free to re-open it if you want to continue progression on this, thanks.

**Comment by ChocolateLoverRaj** [comment]
@serotonyn I think that you should retry the `npm install`. There has been a bigchange to the dependencies used to build the scss, so there is no need for `gulp` now. 



> Closing the PR as it is abandoned by the author. Feel free to re-open it if you want to continue progression on this, thanks.

@TotomInc what stuff needs to get done? I'm interested in reviving this pull request but I'm not sure if / what scss I'll need to change.

**Comment by rhyne-vetcove** [comment]
@ChocolateLoverRaj [This comment](https://github.com/papercss/papercss/pull/169#issuecomment-439729888) should outline what's left to get this ready for launch. But it looks like just the button styles need to be fixed and multiline links need to be supported. Please feel free to open a new PR (against issue #155) if you're interested in getting this across the finish line!

**Comment by rhyneav** [comment]
@ChocolateLoverRaj [This comment](https://github.com/papercss/papercss/pull/169#issuecomment-439729888) should outline what's left to get this ready for launch. But it looks like just the button styles need to be fixed and multiline links need to be supported. Please feel free to open a new PR (against issue #155) if you're interested in getting this across the finish line!

**Pull request closed without merging**
