### PR TITLE
[WIP] Hugo Documentation Site

### PR DESCRIPTION
**Pull request by MunifTanjim**
## Brief description

WORK IN PROGRESS

Hugo conversion

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by MunifTanjim** [comment]
@rhyneav
Here's the initial [preview](https://5a192aa6a114770be2e5b65d--astronaut-pig-36111.netlify.com/).
I didn't do anything new with the design. I just used the current one and divided them into sections.

Can we move to [Netlify](https://www.netlify.com/) permanently for hosting the site?

**Comment by rhyneav** [comment]
This is really cool, thank you for all of the work so far! I especially like how we don't need to escape any more HTML for the code snippets :)

getpapercss.com is already hosted on Netlify, so building/deploying with Hugo shouldn't be an issue on that front. Seriously, Netlify is amazing!

I think one thing that we should change up are the links in the documentation. Instead of it being like the current summary on the site with a list of links, maybe using buttons or even cards might be cool? Just a suggestion, and I'd be happy to spend some time with this as well.

**Comment by MunifTanjim** [comment]
like [this](https://deploy-preview-82--astronaut-pig-36111.netlify.com/docs/components/)?

**Comment by TotomInc** [comment]
It looks cool this way especially on mobile, but on computer it can look better if we can have 3 rows. Have you tried that?

**Comment by MunifTanjim** [comment]
@TotomInc , is it okay now?

By the way, I think, the site should include a sidebar eventually.

**Comment by TotomInc** [comment]
Looks better 👌

**Comment by rhyneav** [comment]
To that point @MunifTanjim, do you think it might be best to include a sidebar now? That way it's in place as more features get added, and to minimize clicking between documentation pages.

**Comment by MunifTanjim** [comment]
Can we easily make one with the current components? Or do we have to use custom css heavily?

If we can use current components for creating sidebar, it makes sense to add it right now @rhyneav

**Comment by TotomInc** [comment]
A sidebar component for PaperCSS would be very good, I agree with your point @MunifTanjim

**Comment by MunifTanjim** [comment]
So, that's for later then? We'll add the sidebar when PaperCSS will have a sidebar component.

**Comment by rhyneav** [comment]
Looks good! Should we try to add this on off of the release 1.2 branch? That way it's not a back and forth struggle of adding new features and getting them into the new documentation before it is released.

**Comment by afzalsayed96** [comment]
I've created a prototype for sidebar which should reduce the number of clicks required to navigate easily

prototype sidebar

**Comment by rhyneav** [comment]
Holy smokes, that is really cool @afzalsayed96!

**Comment by TotomInc** [comment]
It's really beautiful @afzalsayed96, did you plan to open a PR to include the sidebar as a core component of the framework?

**Comment by afzalsayed96** [comment]
@TotomInc I haven't started to code this component yet. The mock-up was created with photoshop just to visualize how a sidebar would look on the landing page. Also yes, this can be included as a core component in the framework. We can create a separate issue for creating/adding sidebar component and assign it to someone who is willing to take this up.

**Comment by rhyneav** [comment]
For the documentation section, until we have a sidebar, would this be an appropriate solution?
image

Every element is linked and can be seen from one page minimizing clicking around. 

Additionally, I think it would be nice to include links in the footer of the documentation to link to other parts of PaperCSS:
image

Again, to minimizing having to go back and forth and to easily be able to go from page to page.

**Comment by afzalsayed96** [comment]
Yess!

**Comment by MunifTanjim** [comment]
@TotomInc, the popover syntax has changed since this documentation markdown file was last updated.
Previously it was: `popover="Popover on left" popover-position="left"`
Now it is: `popover-left="Popover on left"`
It just needs updating.

On a separate note, I don't like either of them and I don't think they will pass the **w3c validation** or are advisable to use.

**Comment by rhyneav** [comment]
Originally, we wanted to keep attributes as concise as possible so they were refactored to only be one attribute instead of two. I meant to keep the old method included in the Less files to avoid it being a breaking change, but clearly forgot. 

Bootstrap uses the `data-*` as @MunifTanjim described. ex: 
```html
<a href="#" data-toggle="tooltip" data-placement="top" title="Hooray!">Hover</a>
```

We need to weigh the pros/cons of either keeping things short and breaking standards, or being verbose and following standards.

**Comment by TotomInc** [comment]
I'll update the popovers to follow the W3C validation, I'll also follow how Bootstrap made their own tooltips.

**Comment by MunifTanjim** [comment]
@rhyneav @TotomInc 
How does it look now?

**Comment by rhyneav** [comment]
I literally said "wow" when I opened up the preview, it looks great! Love the implementation of the side bar on the right! 

The only things I would add would be a label to the docs sidebar (maybe something like this?)
image

The other is just a way to pretty up the initial docs page. 
image
Maybe just mimicking the sidebar here with collapsibles instead of the accordion (since there's more screen space here) would be enough. 

Overall, this is definitely what PaperCSS needs and the documentation overhaul is almost at the finish line. Launching this along with version 1.4 would be perfect!

**Comment by MunifTanjim** [comment]
Rather than duplicating the sidebar in the initial docs page, I've used cards. How about that?

**Comment by Fraham** [comment]
Looks really good

**Comment by rhyneav** [comment]
It definitely looks a lot better as cards, but I'm mostly looking to reduce the amount of clicks within the documentation page. Would listing the components within the category card be a happy medium? That way all available sections are available to click on without taking up much more space.
image

**Comment by MunifTanjim** [comment]
I've tried the list within cards approach. But as the list items length is not same for different sections, they are not aligned correctly and looks disorganized. Let's see if cards within collapsible works.

**Comment by rhyneav** [comment]
Ah I see your point there. I think just going with a simple list instead of cards would be the best solution for now. With cards, it's hard to tell that the sections are even collapsible. 

After this, I think we'll be good to go with the new documentation! Thank you for such a huge overhaul, I'm really excited to get this live and shared with the world :)

**Comment by MunifTanjim** [comment]
@rhyneav done

**Comment by rhyneav** [comment]
You are awesome, thank you!

I'll merge this into develop and then into release-1.4 so that everything is launched together (tomorrow hopefully). I'll leave this PR open through today if anyone has any other comments.

Really excited about this!

**Pull request merged**
