### PR TITLE
Switch components

### PR DESCRIPTION
**Pull request by Phreshhh**
## Brief description

Switch components.

Issue: [Switch component #121](https://github.com/papercss/papercss/issues/121)

## Sample pictures

switch components

## Further details

2x2+1 variable styled switches.

- Default inline switch style with square and circle form. (first 4 row)
- Default outline switch style with square and circle form. (second 4 row)
- Tile styled switches. (last row)

### CODE REVIEW

**Comment by Phreshhh** [comment]
I don't understand this alphabetical sorting.. Why good/better?
The code is much unreadable and cuz' this so hard interpretable for humans, who write it.

**Comment by TotomInc** [comment]
You're right, especially when I see this:

```css
bottom: 0;
cursor: pointer;
left: 0;
position: absolute;
right: 0;
top: 0;
```

and instead as humans we expect to see

```css
position: absolute;
bottom: 0;
left: 0;
right: 0;
top: 0;
cursor: pointer;
```

We will take into consideration proper lint rules when working for the v2 of PaperCSS.

**Comment by Phreshhh** [comment]
Hi @rhyneav !

I want a bit different for better visibility :( , but I changed to variable colors.

**Comment by rhyneav** [comment]
I totally understand, it just makes the framework easier to customize when all of the colors use the variables.

But these look great! I really like the animations on all of them. Thank you for your contribution!

**Pull request merged**
