### PR TITLE
Fix type3 switch component hover effect

### PR DESCRIPTION
**Pull request by kena0ki**
## Brief description
Fixed box-shadow and rotate when the switch component is checked and hovered.

...

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

Before
https://user-images.githubusercontent.com/29003390/204531980-581d4284-e2f6-44ce-b24c-dbd9fe358b18.mov

After
https://user-images.githubusercontent.com/29003390/204532452-c1cecb35-6f4d-43f0-87be-b015951dda22.mov

### CODE REVIEW

**Review by Oli8 — APPROVED** [review]

**Comment by Oli8** [comment]
@kena0ki Could you rebase/fix conflicts?

**Comment by kena0ki** [comment]
@Oli8 Thank you for the review! I fixed conflicts.

**Comment by Oli8** [comment]
@kena0ki Sorry I messed up trying to remove the unnecessary commits :grimacing:  , could you reopen the PR using the changes you should have locally ?

**Comment by kena0ki** [comment]
Sorry for inconvenience🥲

I rebased the branch after I merged it once. I think that's the reason why the unnecessary commits were showed up on GitHub. (I thought It's not a problem for the source code though)

**Comment by kena0ki** [comment]
@Oli8  I created a new PR #302.

**Pull request closed without merging**
