### PR TITLE
fix: Re-added height to navbar icon bars

### LINKED ISSUE #243: Navbar icon not working
A [bug](https://github.com/papercss/papercss/commit/0021424e639db0cdf7df5e4718c53a1e2ca726d3#diff-a9809ee71e5701061936d72fd9e99423864a528b95489e73ab4c0c6efd08f964) was introduced that removed the `height` needed to show bars in the navbar icon.

image

### PR DESCRIPTION
**Pull request by Guergeiro**
## Brief description
Descriptions is given by #243 
This PR, if merged, closes #243

### CODE REVIEW

**Comment by mef** [comment]
Thanks.

It seems that #235 might be closed and replaced by this one...

**Comment by mef** [comment]
Remark: 

```
Performing a commit after pulling this change fails with the following error message:
src/components/_navbar.scss
 24:5  ✖  Expected height to come before width   order/properties-alphabetical-order

pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `stylelint`
pre-commit: hook returned an exit code (2). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

Moving `height` above `width` in _navbar.scss solves the issue.

**Comment by Guergeiro** [comment]
> Moving `height` above `margin` in _navbar.scss solves the issue, as properties are now in alphabetical order.

Done! Let me know if anything else is required.

**Review by rhyneav — APPROVED** [review]
Thank you for the fix! Sorry for such a delay here!

**Pull request merged**
