### PR TITLE
Added the html and css for the navbar

### PR DESCRIPTION
**Pull request by dallinbjohnson**
## Brief description

created a navbar.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

screen shot 2018-04-03 at 1 36 25 am
***
screen shot 2018-04-03 at 1 36 58 am
***
screen shot 2018-04-03 at 1 37 10 am
***
screen shot 2018-04-03 at 1 37 40 am
***
screen shot 2018-04-03 at 1 41 28 am
***
screen shot 2018-04-03 at 1 41 45 am
***

## Further details

...

### CODE REVIEW

**Comment by koester** [comment]
Somehow I can't comment on the files itself. Is this because only maintainers can comment on files directly, or is it because I'm on mobile right now? :thinking:

Either way, thanks for the PR. Great work and nice to see that you figured out the problem. I see a few things that should be fixed before this component will get merged tho.

- There are styles on the HTML and Body tags that should not be needed for the component itself.
- Every value is in pixels. For the modular and responsive approach of PaperCSS those should be in REM. Take a look at the other components to get an idea of what I mean. Only "fixed" values (like for borders or box-shadows) should be in px and pretty much everything else in rem.
- For colors: don't use the hex values of a color directly, but refer to the variables set in `_config.scss` and use those variable names instead.
- try to get used to scss and use the power that it gives you. Try nesting selectors, use variables and the mixins from the config where you can.

**Comment by rhyneav** [comment]
Hmm, let me know if you still can't comment on code via desktop @koester. I thought everyone could comment on files directly.

@dallinbjohnson great work as well so far with this feature! Needs some cleanup as prescribed above, but is coming along nicely!

**Comment by koester** [comment]
@rhyneav it's working on desktop as expected.

@dallinbjohnson I added a few comments to get you started.

**Comment by dallinbjohnson** [comment]
So how do I see the comments that ya'll left? @rhyneav @koester

**Comment by koester** [comment]
I guess i forgot to submit the review :laughing:

**Comment by rhyneav** [comment]
Merged this and closed #146. See #146 for comments.

**Pull request merged**
