### PR TITLE
.feat: create size to .container class

### PR DESCRIPTION
**Pull request by marcuxyz**
## Brief description
This was created for fix containers sizes. These classes can be used with .container helper only.

```scss
.container.container-xs {
  max-width: 750px;
}

.container.container-sm {
  max-width: 900px;
}

.container.container-lg {
  max-width: 1400px;
}

.container.container-xl {
  max-width: 1600px;
}
```
...

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

...

## Further details

...

### CODE REVIEW

**Comment by rhyneav** [comment]
Hey @MarcusMann! Thanks for the PR, and sorry for the delay. I think this is a great idea!

Before merging in, what are your thoughts on using the `responsive-breakpoints` defined in `_config.scss` instead of the hardcoded values you defined. They look like: 

```scss
// Responsive breakpoints
$large-screen: 1200px !default;
$medium-screen: 992px !default;
$small-screen: 768px !default;
$xsmall-screen: 480px !default;
```

This way your container sizes will play nice with the flexbox sizes.

This is a nitpick, but you can also structure your code to take advantage of `scss` to not need to repeat yourself for the class names. You could clean it up to look like:

```scss
.container {
  &.container-xs {
    max-width: $xsmall-screen;
  }
}
```

Please let me know your thoughts!

**Comment by MarcusMann** [comment]
I think it would be simpler to implement and users would be more comfortable with that decision.
Bootstrap, UI KIT and other frameworks follow a **similar pattern**

**Comment by rhyneav** [comment]
Absolutely! If you'd be willing to make those changes, I'd be happy to get this merged in. Please let me know if I can help in any way!

**Comment by marcuxyz** [comment]
Please check again @rhyneav 
Thanks your help.

**Comment by rhyneav** [comment]
Sorry for the delay! This looks great, thank you for making those updates. I'll get this merged in!

**Pull request merged**
